<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="TestsSuite" duration-ms="139692" started-at="2020-07-14T12:26:35 CEST" finished-at="2020-07-14T12:28:55 CEST">
    <groups>
    </groups>
    <test name="Project Test Status" duration-ms="139692" started-at="2020-07-14T12:26:35 CEST" finished-at="2020-07-14T12:28:55 CEST">
      <class name="TestFour">
        <test-method status="PASS" signature="setTest()[pri:0, instance:TestFour@6ec8211c]" name="setTest" is-config="true" duration-ms="8463" started-at="2020-07-14T12:28:07 CEST" finished-at="2020-07-14T12:28:15 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="PASS" signature="fourthTest()[pri:0, instance:TestFour@6ec8211c]" name="fourthTest" duration-ms="9232" started-at="2020-07-14T12:28:15 CEST" finished-at="2020-07-14T12:28:25 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthTest -->
        <test-method status="PASS" signature="closeTest()[pri:0, instance:TestFour@6ec8211c]" name="closeTest" is-config="true" duration-ms="776" started-at="2020-07-14T12:28:25 CEST" finished-at="2020-07-14T12:28:25 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- TestFour -->
      <class name="TestTwo">
        <test-method status="PASS" signature="setTest()[pri:0, instance:TestTwo@64485a47]" name="setTest" is-config="true" duration-ms="7691" started-at="2020-07-14T12:26:52 CEST" finished-at="2020-07-14T12:27:00 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="FAIL" signature="secondTest()[pri:0, instance:TestTwo@64485a47]" name="secondTest" duration-ms="41838" started-at="2020-07-14T12:27:00 CEST" finished-at="2020-07-14T12:27:41 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [159, 953] but found [159, 971]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [159, 953] but found [159, 971]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestTwo.secondTest(TestTwo.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondTest -->
        <test-method status="PASS" signature="closeTest()[pri:0, instance:TestTwo@64485a47]" name="closeTest" is-config="true" duration-ms="1999" started-at="2020-07-14T12:27:41 CEST" finished-at="2020-07-14T12:27:43 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- TestTwo -->
      <class name="TestThree">
        <test-method status="PASS" signature="setTest()[pri:0, instance:TestThree@25bbf683]" name="setTest" is-config="true" duration-ms="7755" started-at="2020-07-14T12:27:43 CEST" finished-at="2020-07-14T12:27:51 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="PASS" signature="thirdTest()[pri:0, instance:TestThree@25bbf683]" name="thirdTest" duration-ms="14607" started-at="2020-07-14T12:27:51 CEST" finished-at="2020-07-14T12:28:06 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method status="PASS" signature="closeTest()[pri:0, instance:TestThree@25bbf683]" name="closeTest" is-config="true" duration-ms="1098" started-at="2020-07-14T12:28:06 CEST" finished-at="2020-07-14T12:28:07 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- TestThree -->
      <class name="TestOne">
        <test-method status="PASS" signature="setTest()[pri:0, instance:TestOne@1990a65e]" name="setTest" is-config="true" duration-ms="9078" started-at="2020-07-14T12:26:35 CEST" finished-at="2020-07-14T12:26:44 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="FAIL" signature="firstTest()[pri:0, instance:TestOne@1990a65e]" name="firstTest" duration-ms="5258" started-at="2020-07-14T12:26:44 CEST" finished-at="2020-07-14T12:26:49 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HCL Gaming Portal - recenzije, vijesti i viÅ¡e za esports, igre i ...] but found [HCL Gaming Portal - recenzije, vijesti i više za esports, igre i ...]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HCL Gaming Portal - recenzije, vijesti i viÅ¡e za esports, igre i ...] but found [HCL Gaming Portal - recenzije, vijesti i više za esports, igre i ...]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestOne.firstTest(TestOne.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstTest -->
        <test-method status="PASS" signature="closeTest()[pri:0, instance:TestOne@1990a65e]" name="closeTest" is-config="true" duration-ms="2513" started-at="2020-07-14T12:26:49 CEST" finished-at="2020-07-14T12:26:52 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- TestOne -->
      <class name="TestFive">
        <test-method status="PASS" signature="setTest()[pri:0, instance:TestFive@7276c8cd]" name="setTest" is-config="true" duration-ms="6336" started-at="2020-07-14T12:28:25 CEST" finished-at="2020-07-14T12:28:32 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setTest -->
        <test-method status="PASS" signature="fifthTest()[pri:0, instance:TestFive@7276c8cd]" name="fifthTest" duration-ms="22132" started-at="2020-07-14T12:28:32 CEST" finished-at="2020-07-14T12:28:54 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fifthTest -->
        <test-method status="PASS" signature="closeTest()[pri:0, instance:TestFive@7276c8cd]" name="closeTest" is-config="true" duration-ms="807" started-at="2020-07-14T12:28:54 CEST" finished-at="2020-07-14T12:28:55 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeTest -->
      </class> <!-- TestFive -->
    </test> <!-- Project Test Status -->
  </suite> <!-- TestsSuite -->
</testng-results>
